version: '3.3'
services:
    server:
      build:
        context: ./source
        dockerfile: ./Dockerfile
      command: bash -c "
        python manage.py migrate
        && python manage.py makemigrations
        && python manage.py runserver 0.0.0.0:8000
        "
      volumes:
        - ./source/:/code
      ports:
        - '8000:8000'
